run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  fast: false
  enable:
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - exportloopref
    - govet
    - gosimple
    - gofmt
    - gofumpt
    - goconst
    - goimports
    - gomnd
    - gocyclo
    - ineffassign
    - lll
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unused
    - whitespace
    - unconvert
    - asciicheck
    - wsl
    - decorder
    - errname
    - errorlint

linters-settings:
  govet:
    check-shadowing: true
  lll:
    line-length: 160
  gomnd:
    checks:
      - case
      - condition
      - return
  goconst:
    ignore-tests: true
  gocyclo:
    min-complexity: 20
  goimports:
    local-prefixes: github.com/jcyamacho-go/httputil
